# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jorge/integrador/proyecto/ui/Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(552, 403)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/proyecto/imagenes/iniciar-sesion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.585, y1:0.881, x2:1, y2:0, stop:0.352273 rgba(18, 19, 48, 255), stop:0.948864 rgba(0, 0, 117, 255));\n"
"font: 10pt \"Malgun Gothic\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(250, 20, 301, 441))
        self.frame.setStyleSheet("background-color: rgb(5, 47, 69);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lblusuario = QtWidgets.QLabel(self.frame)
        self.lblusuario.setGeometry(QtCore.QRect(50, 230, 71, 20))
        self.lblusuario.setStyleSheet("\n"
"color: rgb(170, 255, 255);\n"
"font: 75 12pt \"Arial Narrow\";\n"
"\n"
"")
        self.lblusuario.setObjectName("lblusuario")
        self.txtusuario = QtWidgets.QLineEdit(self.frame)
        self.txtusuario.setGeometry(QtCore.QRect(100, 230, 191, 20))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.txtusuario.setFont(font)
        self.txtusuario.setAccessibleName("")
        self.txtusuario.setAccessibleDescription("")
        self.txtusuario.setAutoFillBackground(False)
        self.txtusuario.setStyleSheet("font: 9pt \"MS Gothic\";\n"
"color:rgb(255, 255, 255);\n"
"border-color: rgb(255, 0, 0);")
        self.txtusuario.setText("")
        self.txtusuario.setFrame(True)
        self.txtusuario.setDragEnabled(False)
        self.txtusuario.setReadOnly(False)
        self.txtusuario.setPlaceholderText("")
        self.txtusuario.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtusuario.setClearButtonEnabled(True)
        self.txtusuario.setObjectName("txtusuario")
        self.iconcontra = QtWidgets.QLabel(self.frame)
        self.iconcontra.setGeometry(QtCore.QRect(10, 260, 31, 31))
        self.iconcontra.setAutoFillBackground(False)
        self.iconcontra.setText("")
        self.iconcontra.setPixmap(QtGui.QPixmap(":/proyecto/imagenes/contrasena.png"))
        self.iconcontra.setScaledContents(True)
        self.iconcontra.setObjectName("iconcontra")
        self.iconusuario = QtWidgets.QLabel(self.frame)
        self.iconusuario.setGeometry(QtCore.QRect(20, 230, 21, 20))
        self.iconusuario.setStyleSheet("background-image: url(:/prefijoNuevo/contrasena.png);\n"
"background-image: url(:/prefijoNuevo/usuario.png);")
        self.iconusuario.setText("")
        self.iconusuario.setPixmap(QtGui.QPixmap(":/proyecto/imagenes/usuario.png"))
        self.iconusuario.setScaledContents(True)
        self.iconusuario.setObjectName("iconusuario")
        self.btningresar = QtWidgets.QPushButton(self.frame)
        self.btningresar.setGeometry(QtCore.QRect(90, 330, 161, 31))
        self.btningresar.setStyleSheet("background-color: rgb(54, 183, 212);\n"
"color:rgb(170, 255, 255)")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/proyecto/imagenes/ingresar (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btningresar.setIcon(icon1)
        self.btningresar.setShortcut("")
        self.btningresar.setObjectName("btningresar")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 270, 171, 20))
        self.lineEdit_2.setAcceptDrops(False)
        self.lineEdit_2.setStyleSheet("font: 9pt \"MS Gothic\";\n"
"color:rgb(255, 255, 255);\n"
"border-color:  rgb(255, 0, 0);")
        self.lineEdit_2.setDragEnabled(False)
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lblcontra = QtWidgets.QLabel(self.frame)
        self.lblcontra.setGeometry(QtCore.QRect(50, 270, 71, 20))
        self.lblcontra.setStyleSheet("\n"
"color: rgb(170, 255, 255);\n"
"font: 75 12pt \"Arial Narrow\";\n"
"\n"
"")
        self.lblcontra.setObjectName("lblcontra")
        self.imglogin = QtWidgets.QLabel(self.frame)
        self.imglogin.setGeometry(QtCore.QRect(100, 90, 131, 121))
        self.imglogin.setStyleSheet("background-image: url(:/programador.png);")
        self.imglogin.setText("")
        self.imglogin.setPixmap(QtGui.QPixmap(":/proyecto/imagenes/programador.png"))
        self.imglogin.setScaledContents(True)
        self.imglogin.setObjectName("imglogin")
        self.lbl = QtWidgets.QLabel(self.centralwidget)
        self.lbl.setEnabled(False)
        self.lbl.setGeometry(QtCore.QRect(0, 10, 541, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        font.setKerning(True)
        self.lbl.setFont(font)
        self.lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl.setStyleSheet("\n"
"\n"
"color: rgb(54, 183, 212);\n"
"font: 75 30pt \"Arial Narrow\";\n"
"\n"
"\n"
"\n"
"")
        self.lbl.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl.setObjectName("lbl")
        self.imgcarro = QtWidgets.QLabel(self.centralwidget)
        self.imgcarro.setGeometry(QtCore.QRect(10, 90, 241, 291))
        self.imgcarro.setStyleSheet("")
        self.imgcarro.setText("")
        self.imgcarro.setPixmap(QtGui.QPixmap(":/proyecto/imagenes/carros.png"))
        self.imgcarro.setScaledContents(True)
        self.imgcarro.setObjectName("imgcarro")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.lblusuario.setText(_translate("MainWindow", "Usuario"))
        self.btningresar.setText(_translate("MainWindow", "Ingresar "))
        self.lblcontra.setText(_translate("MainWindow", "Contraseña"))
        self.lbl.setText(_translate("MainWindow", "Registro de Estacionamiento "))
import recursos_rc
